# Generated by Django 4.0.3 on 2023-05-25 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_customgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.ManyToManyField(related_name='custom_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
