# Generated by Django 2.2.4 on 2023-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
