# Generated by Django 2.2.4 on 2023-05-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='subject',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
