# Generated by Django 2.2.4 on 2023-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_question_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
