# Generated by Django 3.2.19 on 2023-05-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
