# Generated by Django 3.2.19 on 2023-05-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_delete_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
