# Generated by Django 3.2.19 on 2023-05-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_question_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='payment',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
