# Generated by Django 4.0.3 on 2023-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_remove_question_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='npz',
            field=models.FileField(blank=True, null=True, upload_to='npz/'),
        ),
    ]
