# Generated by Django 4.0.3 on 2023-05-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0017_question_npz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
